export const AttendanceArray = [
    {
        name: 'Austin Stack',
        avatar: 'https://www.w3schools.com/w3images/avatar5.png',
        id: '615ed6cccf465b99b60dbf38',
        notAttempted: '10%',
        submitted: '85%',
        approved: '80%',
        status: 'Approved',
    },
    {
        name: 'Ahmed Elarosi',
        avatar: 'https://www.w3schools.com/howto/img_avatar2.png',
        id: '615ed6cccf465b99b60dbf39',
        notAttempted: '20%',
        submitted: '80%',
        approved: '70%',
        status: 'Approved',
    },
    {
        name: 'Victor Maragioglio',
        avatar: 'https://www.w3schools.com/w3images/avatar6.png',
        id: '615ed6cccf465b99b60dbf3a',
        notAttempted: '15%',
        submitted: '80%',
        approved: '80%',
        status: 'Approved',
    },
    {
        name: 'Alexey Kachalov',
        avatar: 'https://www.svgrepo.com/show/163162/avatar.svg',
        id: '615ed6cccf465b99b60dbf3b',
        notAttempted: '20%',
        submitted: '80%',
        approved: '80%',
        status: 'Approved',
    },
    {
        name: 'Asif Mohiuddin',
        avatar: 'https://www.svgrepo.com/show/53617/avatar.svg',
        id: '615ed6cccf465b99b60dbf3c',
        notAttempted: '45%',
        submitted: '45%',
        approved: '20%',
        status: 'Approved',
    },
];
